CREATE DATABASE taskforce
  DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;


USE taskforce;

CREATE TABLE categories (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	icon VARCHAR(20) NOT NULL
);

CREATE TABLE cities (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	city VARCHAR(100) NOT NULL,
	lat DOUBLE UNSIGNED NOT NULL,
	`long` DOUBLE UNSIGNED NOT NULL
);

CREATE TABLE opinions (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	dt_add DATETIME NOT NULL,
	rate INT UNSIGNED NOT NULL,
	description TEXT NOT NULL
);

CREATE TABLE profiles (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	address VARCHAR(700) NOT NULL,
	bd DATETIME NOT NULL,
	about TEXT NOT NULL,
	phone VARCHAR(100) NOT NULL,
	skype VARCHAR(100) NOT NULL
);

CREATE TABLE replies (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	dt_add DATETIME NOT NULL,
	rate INT UNSIGNED NOT NULL,
	description TEXT NOT NULL
);

CREATE TABLE tasks (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	dt_add DATETIME NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  path VARCHAR(100),
	description TEXT NOT NULL,
  expire DATETIME,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(700),
  budget INT UNSIGNED,
  city_id INT UNSIGNED,
  lat DOUBLE UNSIGNED,
	`long` DOUBLE UNSIGNED
);

CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	dt_add DATETIME NOT NULL,
  email VARCHAR(72) NOT NULL,
	name VARCHAR(100) NOT NULL,
	password CHAR(64) NOT NULL
);

ALTER TABLE tasks ADD FOREIGN KEY (category_id) REFERENCES categories(id);
ALTER TABLE tasks ADD FOREIGN KEY (city_id) REFERENCES cities(id);
